name = "vitessedge"
type = "javascript"
account_id = "7cfd6f38341c1adc0cbb70ff035ca0af"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "dist/client"
entry-point = "."

[build]
command = ""
watch_dir = "dist/worker"

[build.upload]
format = "service-worker"